//! Auto IR — the typed task graph at the center of the Auto toolchain.
//!
//! A [`Graph`] is a DAG of typed [`Node`]s connected by dataflow [`Edge`]s,
//! with [`Region`]s grouping nodes for later extraction passes. Every node
//! declares its capability effects, memory effects, uncertainty class, and
//! resource bounds.
//!
//! Serialization is flatbuffers with a byte-stable round-trip:
//! `from_bytes(&to_bytes(g)?)? == g`, and re-serializing the decoded graph
//! produces byte-identical output. Equal graphs serialize to equal bytes
//! (canonical encoding via ordered containers).
//!
//! The normative wire spec is `spec/ir.md`; the schema is `schema/ir.fbs`.

mod effects;
pub mod examples;
mod graph;
mod ids;
mod node;
mod render;
mod ser;
mod types;

pub use effects::{CapabilityEffect, MemoryEffect, Uncertainty};
pub use graph::{Edge, Graph, PortDir, Region, SCHEMA_VERSION, ValidationError};
pub use ids::{GraphId, NodeId, RegionId};
pub use node::{Node, NodeKind, Port, ResourceBounds};
pub use render::render;
pub use ser::{IrError, from_bytes, to_bytes};
pub use types::ValueType;

// Flatbuffers accessors generated by build.rs (`flatc --rust` over schema/ir.fbs).
//
// allow(unsafe_code): the generated reader uses unchecked buffer accessors;
// every buffer this crate touches goes through the `flatbuffers::root` verifier
// first (see ser.rs::from_bytes), which is the safety precondition those
// accessors document.
// allow(warnings, clippy::all): generated code is exempt from the workspace
// lint policy — it is never edited by hand.
#[allow(unsafe_code, warnings, clippy::all)]
mod fbgen {
    include!(concat!(env!("OUT_DIR"), "/ir_generated.rs"));
}
pub(crate) use fbgen::auto::ir::fb;
